// <auto-generated />
using System;
using Investment.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Investment.Persistence.Migrations
{
    [DbContext(typeof(InvestmentDbContext))]
    [Migration("20260928145255_FinancialReportLines")]
    partial class FinancialReportLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Investment.Domain.Market.DailyPrice", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("high");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<bool>("IsHalted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_halted");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("open");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<decimal>("TradingValueEstimate")
                        .HasPrecision(24, 2)
                        .HasColumnType("numeric(24,2)")
                        .HasColumnName("trading_value_estimate");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Ticker", "Date")
                        .HasName("pk_daily_prices");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_daily_prices_date");

                    b.ToTable("daily_prices", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Market.Disclosure", b =>
                {
                    b.Property<string>("ReceiptNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt_no");

                    b.Property<string>("CorpClass")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("corp_class");

                    b.Property<string>("CorpCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("corp_code");

                    b.Property<string>("CorpName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("corp_name");

                    b.Property<string>("DisclosureType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("disclosure_type");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event");

                    b.Property<string>("Filer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("filer");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<bool>("IsCorrection")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correction");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<string>("Remark")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("remark");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("report_name");

                    b.Property<string>("Ticker")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.HasKey("ReceiptNo")
                        .HasName("pk_disclosures");

                    b.HasIndex("Event", "ReceiptDate")
                        .HasDatabaseName("ix_disclosures_event_receipt_date");

                    b.HasIndex("Ticker", "ReceiptDate")
                        .HasDatabaseName("ix_disclosures_ticker_receipt_date");

                    b.ToTable("disclosures", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Market.FinancialReportLine", b =>
                {
                    b.Property<string>("CorpCode")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("corp_code");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<string>("ReportCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("report_code");

                    b.Property<string>("FsDiv")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("fs_div");

                    b.Property<string>("Account")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account");

                    b.Property<decimal?>("PriorAmount")
                        .HasPrecision(24)
                        .HasColumnType("numeric(24,0)")
                        .HasColumnName("prior_amount");

                    b.Property<decimal?>("PriorCumulative")
                        .HasPrecision(24)
                        .HasColumnType("numeric(24,0)")
                        .HasColumnName("prior_cumulative");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt_no");

                    b.Property<decimal?>("ThisAmount")
                        .HasPrecision(24)
                        .HasColumnType("numeric(24,0)")
                        .HasColumnName("this_amount");

                    b.Property<decimal?>("ThisCumulative")
                        .HasPrecision(24)
                        .HasColumnType("numeric(24,0)")
                        .HasColumnName("this_cumulative");

                    b.Property<string>("Ticker")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.HasKey("CorpCode", "FiscalYear", "ReportCode", "FsDiv", "Account")
                        .HasName("pk_financial_report_lines");

                    b.HasIndex("Ticker", "ReceiptDate")
                        .HasDatabaseName("ix_financial_report_lines_ticker_receipt_date");

                    b.ToTable("financial_report_lines", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Market.IndexPrice", b =>
                {
                    b.Property<string>("IndexCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("index_code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("high");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("open");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("IndexCode", "Date")
                        .HasName("pk_index_prices");

                    b.ToTable("index_prices", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Market.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("items_failed");

                    b.Property<int>("ItemsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("items_requested");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("RowsUpserted")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_upserted");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_runs");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Market.MarketRegimeDay", b =>
                {
                    b.Property<string>("IndexCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("index_code");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<double>("RealizedVol20")
                        .HasColumnType("double precision")
                        .HasColumnName("realized_vol20");

                    b.Property<double>("Sma200")
                        .HasColumnType("double precision")
                        .HasColumnName("sma200");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trend");

                    b.Property<double>("VolThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("vol_threshold");

                    b.Property<string>("Volatility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("volatility");

                    b.HasKey("IndexCode", "Date")
                        .HasName("pk_market_regimes");

                    b.ToTable("market_regimes", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Market.Security", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.Property<DateOnly?>("DelistedDate")
                        .HasColumnType("date")
                        .HasColumnName("delisted_date");

                    b.Property<string>("DelistingReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("delisting_reason");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateOnly?>("ListedDate")
                        .HasColumnType("date")
                        .HasColumnName("listed_date");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("market");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sector")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sector");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Ticker")
                        .HasName("pk_securities");

                    b.ToTable("securities", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Market.SplitEvent", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<double>("PriceFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("price_factor");

                    b.Property<bool>("SourceVolumeAdjusted")
                        .HasColumnType("boolean")
                        .HasColumnName("source_volume_adjusted");

                    b.Property<double>("VolumeCorrection")
                        .HasColumnType("double precision")
                        .HasColumnName("volume_correction");

                    b.HasKey("Ticker", "EventDate")
                        .HasName("pk_split_events");

                    b.ToTable("split_events", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestEquityPoint", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Cash")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("cash");

                    b.Property<decimal>("GrossEquity")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("gross_equity");

                    b.Property<decimal>("NetEquity")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("net_equity");

                    b.Property<int>("Positions")
                        .HasColumnType("integer")
                        .HasColumnName("positions");

                    b.HasKey("RunId", "Date")
                        .HasName("pk_backtest_equity");

                    b.ToTable("backtest_equity", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestMetric", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Basis")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("basis");

                    b.Property<double>("AnnualTurnover")
                        .HasColumnType("double precision")
                        .HasColumnName("annual_turnover");

                    b.Property<double>("AvgDailyReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_daily_return");

                    b.Property<double>("AvgHoldingSessions")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_holding_sessions");

                    b.Property<double>("AvgLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_loss");

                    b.Property<double>("AvgProfit")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_profit");

                    b.Property<double>("BenchmarkReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("benchmark_return");

                    b.Property<double>("Cagr")
                        .HasColumnType("double precision")
                        .HasColumnName("cagr");

                    b.Property<double>("DailyReturnStdev")
                        .HasColumnType("double precision")
                        .HasColumnName("daily_return_stdev");

                    b.Property<double>("ExpectedValuePerTrade")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_value_per_trade");

                    b.Property<double>("ExpectedValuePerTradeKrw")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_value_per_trade_krw");

                    b.Property<double>("ExpectedValueTStat")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_value_t_stat");

                    b.Property<double>("Exposure")
                        .HasColumnType("double precision")
                        .HasColumnName("exposure");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("double precision")
                        .HasColumnName("max_drawdown");

                    b.Property<int>("NumberOfTrades")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_trades");

                    b.Property<double>("ProfitFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("profit_factor");

                    b.Property<double>("Sharpe")
                        .HasColumnType("double precision")
                        .HasColumnName("sharpe");

                    b.Property<double>("Sortino")
                        .HasColumnType("double precision")
                        .HasColumnName("sortino");

                    b.Property<double>("TotalCosts")
                        .HasColumnType("double precision")
                        .HasColumnName("total_costs");

                    b.Property<double>("TotalReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("total_return");

                    b.Property<int>("TradingDays")
                        .HasColumnType("integer")
                        .HasColumnName("trading_days");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision")
                        .HasColumnName("win_rate");

                    b.HasKey("RunId", "Basis")
                        .HasName("pk_backtest_metrics");

                    b.ToTable("backtest_metrics", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeCommit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_commit");

                    b.Property<bool>("CodeDirty")
                        .HasColumnType("boolean")
                        .HasColumnName("code_dirty");

                    b.Property<string>("CostModelJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cost_model_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_hash");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_source");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("engine_version");

                    b.Property<string>("HaltReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("halt_reason");

                    b.Property<DateOnly?>("HaltedOn")
                        .HasColumnType("date")
                        .HasColumnName("halted_on");

                    b.Property<decimal>("InitialCapital")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("initial_capital");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_run_id");

                    b.Property<string>("ResultHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("result_hash");

                    b.Property<string>("RiskLimitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_limits_json");

                    b.Property<string>("RunKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("run_kind");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_version_id");

                    b.Property<Guid?>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.Property<string>("UniverseHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("universe_hash");

                    b.Property<string>("UniverseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("universe_json");

                    b.HasKey("Id")
                        .HasName("pk_backtest_runs");

                    b.HasIndex("ParentRunId")
                        .HasDatabaseName("ix_backtest_runs_parent_run_id");

                    b.HasIndex("StrategyVersionId")
                        .HasDatabaseName("ix_backtest_runs_strategy_version_id");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_backtest_runs_study_id");

                    b.ToTable("backtest_runs", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Costs")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("costs");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("entry_price");

                    b.Property<string>("EntryReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entry_reason");

                    b.Property<decimal>("EntryReferencePrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("entry_reference_price");

                    b.Property<double>("EntryScore")
                        .HasColumnType("double precision")
                        .HasColumnName("entry_score");

                    b.Property<DateOnly>("EntrySignalDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_signal_date");

                    b.Property<DateOnly>("ExitDate")
                        .HasColumnType("date")
                        .HasColumnName("exit_date");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exit_reason");

                    b.Property<decimal>("ExitReferencePrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("exit_reference_price");

                    b.Property<decimal>("GrossPnl")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("gross_pnl");

                    b.Property<double>("GrossReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("gross_return");

                    b.Property<int>("HoldingSessions")
                        .HasColumnType("integer")
                        .HasColumnName("holding_sessions");

                    b.Property<decimal>("NetPnl")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("net_pnl");

                    b.Property<double>("NetReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("net_return");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.HasKey("Id")
                        .HasName("pk_backtest_trades");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_backtest_trades_run_id");

                    b.ToTable("backtest_trades", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.ExperimentFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hypothesis");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<string>("RegimeNotes")
                        .HasColumnType("text")
                        .HasColumnName("regime_notes");

                    b.Property<DateTimeOffset>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("strategy_id");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_version_id");

                    b.Property<DateOnly>("TestFrom")
                        .HasColumnType("date")
                        .HasColumnName("test_from");

                    b.Property<DateOnly>("TestTo")
                        .HasColumnType("date")
                        .HasColumnName("test_to");

                    b.HasKey("Id")
                        .HasName("pk_experiment_failures");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("ix_experiment_failures_strategy_id");

                    b.HasIndex("StrategyVersionId")
                        .HasDatabaseName("ix_experiment_failures_strategy_version_id");

                    b.ToTable("experiment_failures", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.ResearchStudy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeCommit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_commit");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hypothesis");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_json");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("strategy_id");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("summary_json");

                    b.Property<int>("VariantsTried")
                        .HasColumnType("integer")
                        .HasColumnName("variants_tried");

                    b.HasKey("Id")
                        .HasName("pk_research_studies");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("ix_research_studies_strategy_id");

                    b.ToTable("research_studies", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.StrategyDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("family");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hypothesis");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_strategies");

                    b.ToTable("strategies", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.StrategyEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria_json");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_json");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reasons")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reasons");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_version_id");

                    b.Property<Guid?>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_strategy_evaluations");

                    b.HasIndex("StrategyVersionId")
                        .HasDatabaseName("ix_strategy_evaluations_strategy_version_id");

                    b.ToTable("strategy_evaluations", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.StrategyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LogicVersion")
                        .HasColumnType("integer")
                        .HasColumnName("logic_version");

                    b.Property<string>("ParametersHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parameters_hash");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("strategy_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_strategy_versions");

                    b.HasIndex("StrategyId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_strategy_versions_strategy_id_version");

                    b.HasIndex("StrategyId", "LogicVersion", "ParametersHash")
                        .IsUnique()
                        .HasDatabaseName("ix_strategy_versions_strategy_id_logic_version_parameters_hash");

                    b.ToTable("strategy_versions", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Trading.PaperEquityPoint", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Cash")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("cash");

                    b.Property<decimal>("GrossEquity")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("gross_equity");

                    b.Property<decimal>("NetEquity")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("net_equity");

                    b.Property<int>("Positions")
                        .HasColumnType("integer")
                        .HasColumnName("positions");

                    b.Property<string>("Regime")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("regime");

                    b.HasKey("SessionId", "Date")
                        .HasName("pk_paper_equity");

                    b.ToTable("paper_equity", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Trading.PaperOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ExpectedReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_return");

                    b.Property<DateOnly?>("FillDate")
                        .HasColumnType("date")
                        .HasColumnName("fill_date");

                    b.Property<decimal?>("FillPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("fill_price");

                    b.Property<long?>("FilledQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("filled_quantity");

                    b.Property<string>("MarketCondition")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("market_condition");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("side");

                    b.Property<DateOnly>("SignalDate")
                        .HasColumnType("date")
                        .HasColumnName("signal_date");

                    b.Property<decimal>("SignalPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("signal_price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.HasKey("Id")
                        .HasName("pk_paper_orders");

                    b.HasIndex("SessionId", "SignalDate")
                        .HasDatabaseName("ix_paper_orders_session_id_signal_date");

                    b.ToTable("paper_orders", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Trading.PaperRunLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeCommit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_commit");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_hash");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("ProcessedFrom")
                        .HasColumnType("date")
                        .HasColumnName("processed_from");

                    b.Property<DateOnly?>("ProcessedTo")
                        .HasColumnType("date")
                        .HasColumnName("processed_to");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("SessionsProcessed")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_processed");

                    b.HasKey("Id")
                        .HasName("pk_paper_runs");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_paper_runs_session_id");

                    b.ToTable("paper_runs", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Trading.PaperSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockedRegimesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blocked_regimes_json");

                    b.Property<string>("CostModelJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cost_model_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EvidenceEvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_evaluation_id");

                    b.Property<double>("ExpectedEvPerTrade")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_ev_per_trade");

                    b.Property<decimal>("InitialCapital")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("initial_capital");

                    b.Property<DateOnly?>("LastProcessedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_processed_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<string>("RiskLimitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_limits_json");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StoppedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stopped_reason");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("strategy_id");

                    b.Property<Guid>("StrategyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_version_id");

                    b.Property<string>("UniverseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("universe_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_paper_sessions");

                    b.HasIndex("StrategyVersionId")
                        .HasDatabaseName("ix_paper_sessions_strategy_version_id");

                    b.ToTable("paper_sessions", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Trading.PaperTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ActualReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_return");

                    b.Property<decimal>("Costs")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("costs");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("entry_price");

                    b.Property<DateOnly>("EntryTime")
                        .HasColumnType("date")
                        .HasColumnName("entry_time");

                    b.Property<decimal>("ExitPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("exit_price");

                    b.Property<string>("ExitReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exit_reason");

                    b.Property<DateOnly>("ExitTime")
                        .HasColumnType("date")
                        .HasColumnName("exit_time");

                    b.Property<double>("ExpectedReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_return");

                    b.Property<double>("GrossReturn")
                        .HasColumnType("double precision")
                        .HasColumnName("gross_return");

                    b.Property<int>("HoldingSessions")
                        .HasColumnType("integer")
                        .HasColumnName("holding_sessions");

                    b.Property<string>("MarketCondition")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("market_condition");

                    b.Property<decimal>("NetPnl")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("net_pnl");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("result");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<decimal>("SignalPrice")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("signal_price");

                    b.Property<DateOnly>("SignalTime")
                        .HasColumnType("date")
                        .HasColumnName("signal_time");

                    b.Property<decimal?>("StopLoss")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("stop_loss");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("strategy_id");

                    b.Property<decimal?>("TakeProfit")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("take_profit");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ticker");

                    b.HasKey("Id")
                        .HasName("pk_paper_trades");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_paper_trades_session_id");

                    b.ToTable("paper_trades", (string)null);
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestEquityPoint", b =>
                {
                    b.HasOne("Investment.Domain.Research.BacktestRun", null)
                        .WithMany("Equity")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backtest_equity_backtest_runs_run_id");
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestMetric", b =>
                {
                    b.HasOne("Investment.Domain.Research.BacktestRun", null)
                        .WithMany("Metrics")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backtest_metrics_backtest_runs_run_id");
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestRun", b =>
                {
                    b.HasOne("Investment.Domain.Research.StrategyVersion", "StrategyVersion")
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_backtest_runs_strategy_versions_strategy_version_id");

                    b.Navigation("StrategyVersion");
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestTrade", b =>
                {
                    b.HasOne("Investment.Domain.Research.BacktestRun", null)
                        .WithMany("Trades")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backtest_trades_backtest_runs_run_id");
                });

            modelBuilder.Entity("Investment.Domain.Research.ExperimentFailure", b =>
                {
                    b.HasOne("Investment.Domain.Research.StrategyVersion", null)
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_experiment_failures_strategy_versions_strategy_version_id");
                });

            modelBuilder.Entity("Investment.Domain.Research.StrategyEvaluation", b =>
                {
                    b.HasOne("Investment.Domain.Research.StrategyVersion", null)
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_strategy_evaluations_strategy_versions_strategy_version_id");
                });

            modelBuilder.Entity("Investment.Domain.Research.StrategyVersion", b =>
                {
                    b.HasOne("Investment.Domain.Research.StrategyDefinition", "Strategy")
                        .WithMany("Versions")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_strategy_versions_strategies_strategy_id");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("Investment.Domain.Trading.PaperSession", b =>
                {
                    b.HasOne("Investment.Domain.Research.StrategyVersion", null)
                        .WithMany()
                        .HasForeignKey("StrategyVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_paper_sessions_strategy_versions_strategy_version_id");
                });

            modelBuilder.Entity("Investment.Domain.Research.BacktestRun", b =>
                {
                    b.Navigation("Equity");

                    b.Navigation("Metrics");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Investment.Domain.Research.StrategyDefinition", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
